const Images = {
    GoogleCloud: require("../asset/images/google-cloud-seeklogo.com.png").default,
    Amazon: require("../asset/images/amazon-web-services-2.png").default,
    Kubernets: require("../asset/images/kubernets.png").default,
    Docker: require("../asset/images/docker.png").default,
    Terraform: require("../asset/images/terraform-enterprise.png").default,
    Vagrant: require("../asset/images/vagrant.png").default,
    Jenkins: require("../asset/images/jenkins.png").default,
    Maven: require("../asset/images/maven.png").default,
    Beam: require("../asset/images/beam-1.png").default,
    Grafana: require("../asset/images/grafana.png").default,
    Kafka: require("../asset/images/kafka.png").default,
    Elastic: require("../asset/images/elastic.png").default,
    Mysql: require("../asset/images/mysql.png").default,
    Postgresql: require("../asset/images/postgresql.png").default,
    Mongodb: require("../asset/images/mongodb.png").default,
    Cassandra: require("../asset/images/cassandra.png").default,
    Redis: require("../asset/images/redis.png").default,
    Numpy: require("../asset/images/numpy.png").default,
    Pandas: require("../asset/images/pandas.png").default,
    Tensorflow: require("../asset/images/tensorflow-2.png").default,
    Opencv: require("../asset/images/opencv.png").default,
    GoogleAnalytics: require("../asset/images/google-analytics-3.png").default,
    Hubs: require("../asset/images/hubs.png").default,
    Unity: require("../asset/images/unity-69.png").default,
    Blender: require("../asset/images/logo-blender.png").default,
    Flutter: require("../asset/images/flutter.png").default,
    Android: require("../asset/images/android-5.png").default,
    Firebase: require("../asset/images/firebase-1.png").default,
    Spring: require("../asset/images/spring-3.png").default,
    Django: require("../asset/images/django.png").default,
    Flask: require("../asset/images/flask.png").default,
    NodeJs: require("../asset/images/nodejs-1.png").default,
    Electron: require("../asset/images/electron-4.png").default,
    Vue: require("../asset/images/vue-9.png").default,
    React: require("../asset/images/react.png").default,
    
    
    Java: require("../asset/images/java.png").default,
    C: require("../asset/images/c.png").default,
    C2: require("../asset/images/c--4.png").default,
    Python: require("../asset/images/python-5.png").default,
    Kotlin: require("../asset/images/kotlin-1.png").default,
    Scala: require("../asset/images/scala-4.png").default,
    Golang: require("../asset/images/golang-gopher.png").default,
    Dart: require("../asset/images/dart.png").default,
    javascript: require("../asset/images/javascript.png").default,


}
export default Images